/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "registro": [],
    "registro.store": [],
    "login": [],
    "login.store": [],
    "logout.store": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.send": [],
    "dashboard": [],
    "Presupuestos.create": [],
    "Presupuestos.store": [],
    "Presupuestos.edit": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.show": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.update": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.destroy": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.store": [
        {
            "name": "presupuesto",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
