/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "registro": [],
    "registro.store": [],
    "login": [],
    "login.store": [],
    "logout.store": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.send": [],
    "dashboard": [],
    "Presupuestos.create": [],
    "Presupuestos.store": [],
    "Presupuestos.edit": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.show": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.update": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.destroy": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.store": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.update": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.destroy": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "settings.profile": [],
    "settings.profile.update": [],
    "settings.password": [],
    "settings.password.update": [],
    "Presupuestos.chat": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "Presupuestos.addimage": [
        {
            "name": "presupuesto",
            "required": true,
            "binding": "id"
        }
    ],
    "subscription.checkout": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "billing.success": [],
    "billing.cancel": [],
    "plans": [],
    "subscription.manage": [],
    "subscription.swap": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "subscription.cancel": [],
    "subscription.resume": [],
    "billing": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
